### ISSUE TITLE
Support for specifying more than one artifactory paths for triggerring a build

### ISSUE THREAD

**Issue by souris4science** [jfrog/jenkins-artifactory-plugin#100]
It would be convenient to be able to specify more than one paths  that will be checked for changes in order to trigger a build (e.g. in the same artifactory server and separated by semicolon in the path field).

Also, is there any support for define this trigger in the pippeline script using the declarative syntax, e.g. `triggers { ... }` ?

Thanks in advance!

**Comment by alexanderrtaylor** [comment]
Looks like https://github.com/jfrog/jenkins-artifactory-plugin/pull/160 already solved this

**Comment by eyalbe4** [comment]
Thanks @alexanderrtaylor. Correct.
This should be part of the upcoming release. I'm closing this issue, since we have #160 which also includes the JIRA issue for tracking.
@souris4science - defining a trigger using a pipeline API is currently not supported.
Can you please open a new issue for it and elaborate more about the user case?

**Comment by souris4science** [comment]
Thanks @alexanderrtaylor!
@eyalbe4 - Just created #175
