### ISSUE TITLE
Deploy failed to Artifactory after upgrade to version 3.11.4

### ISSUE THREAD

**Issue by tiendungitd** [jfrog/jenkins-artifactory-plugin#506]
**Describe the bug**
I've just upgraded Artifactory plugin from version 3.6.2 to 3.11.4. after that I could not deploy artifact to Artifactory anymore, it show the error:
`java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;`
Please see the log in attachment.
[upload_failed.log](https://github.com/jfrog/jenkins-artifactory-plugin/files/6637842/upload_failed.log)
**Versions**
Jenkins 2.263.4
Upgrade Artifactory plugin version 3.11.4
Artifactory OSS server 6.23.16

**Comment by yahavi** [comment]
@tiendungitd 
Thanks for reporting this issue.

Jenkins Artifactory Plugin 3.11.4 is using IOUtils.toString(InputStream, Charset), which presented in Apache IOUtils 2.3, April 2012. For some reason, the Maven resolver chose Apache IOUtils below 2.3, which is very old. This may occur due to another Jenkins plugin that utilizes this version.

We created jfrog/build-info#516 to handle this issue by using [IOUtils.toString(InputStream, String)](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/IOUtils.html#toString-java.io.InputStream-java.lang.String-) which is presented in 2.1.

We'll keep you updated.

**Comment by ryan-25** [comment]
Same issue here with 
**Versions**
Jenkins 2.289.1
Upgrade Artifactory plugin version 3.11.4
Artifactory OSS server 7.3.2

**Comment by tiendungitd** [comment]
Hi @yahavi 
Will the next release of Artifactory plugin  include this bug fix?

**Comment by yahavi** [comment]
Yes, @tiendungitd.
Feel free to upgrade to 3.12.1.
We'd appreciate your feedback on that.
