### ISSUE TITLE
Collecting build issues fail with 'git revision doesn't exist in the range'

### ISSUE THREAD

**Issue by Or-Geva** [jfrog/jenkins-artifactory-plugin#620]
**Describe the bug**
When collecting issues, the current build is trying to read the old git commit hash and fails. As a result, no issues are added to build-info.json

 ** Log message**
 `Revision: *** that was fetched from latest build info does not exist in the git revision range. No new issues are added.`
 
**So what's causing the problem?**
The logic behind collect build issues is:

  1. Get the latest build number of the current build (by its name)
  2. Extract the revision from it
  3. Collect new issues from the last revision message to the most up-to-date revision. 
  
 This logic is here to protect us from collecting old issues, again and again. Issues that were collected shouldn’t be collected again.
 This means that if the last build revision is lost due to rebase/reset, we won't be able to collect issues.
 
 **Are there any workarounds?**
 Currently no. However, the next build, which depends on the current build revision, would work if it finds the revision.
 
**What can we do to overcome this problem?**
Basically, the commit revision, from the last build, tells us where it stopped collecting issues, and where we are supposed to start. Without the revision, we will collect the same issues as the previous build did.

The idea of revision is like time-series to us, that connects each build with another. We need to use an alternative time series if we lost the revision so the chain won't break. I propose to use  'timestamp', it is included in every commit, so we can add it to every build like revisions, and it is time-series based :)

The solution will require two changes:

1. Add a new field to the VCS in the build-info schema name ‘timestamp’. This is how it would look like:
```
{
   "revision":"123",
   "message":"bugfix - foo",
   "branch":"master",
   "url":"www",
   "timestamp": "111"
}
```
2. If the revision is not found, run the following git  command:
```
git log --date=unix --since=111
```
This way, we will be able to start collecting build issues from the last build.

**Comment by bverkron** [comment]
> This means that if the last build revision is lost due to rebase/reset, we won't be able to collect issues.
This scenario can happen in other ways as well. I haven't been able confirm but I think what happened in one case for me was something along the lines of:
* Jenkins job run against alternate branch of repo (for testing some possible changes)
* Build.json created with a revision from that alternate branch
* Jenkins job run against master branch again
* Revision was not in the master branch that got checked out into the workspace thus `...build info does not exist in the git revision range`

Probably other ways this can happen as well.

> Issues that were collected shouldn’t be collected again.
I'm curious about this statement. Do you mean the issue(s) should not be collected again against that specific build or at all even for subsequent builds? Regardless I have a build in Artifactory that has the same issue key 7 times. Each appears to be treated uniquely because the summary string after the issue key in the commit message was unique.

![image](https://user-images.githubusercontent.com/19174503/150577756-e004f839-ed12-470f-b51b-ade4b7d3ae25.png)

This is what the Jenkins log contained:
```
Retrieving build artifacts report from: /api/build/patternArtifacts
Executing command: /bin/sh -c git log --pretty=format:%s -100 2a84b831102f2e74ee02c1c56d43dc0c9843e5b1..
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-629 to the build-info
Added issue: AS-629 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-629 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-629 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
Added issue: AS-624 to the build-info
```

**Comment by Or-Geva** [comment]
Thanks for the great feedback @bverkron !. 


> > Issues that were collected shouldn’t be collected again.
> 
> I'm curious about this statement. Do you mean the issue(s) should not be collected again against that specific build or at all even for subsequent builds? 

The list of issues is collected by Jenkins from the git commit messages. We compare each commits message to the key/summary group index that you configured. Now, we don't want to include issues from the previous build(s), otherwise,  the build-info will be spammed with duplicate issues. Therefore, we need to have the revision from the previous build to collect only new commits issues and to add them to the current build. Although you can set the `aggregate` flag to true if you wish to include issues from previous builds (see [here](https://www.jfrog.com/confluence/display/JFROG/Declarative+Pipeline+Syntax#DeclarativePipelineSyntax-CollectingBuildIssues) all the available flags).

> > This means that if the last build revision is lost due to rebase/reset, we won't be able to collect issues.
> > This scenario can happen in other ways as well. I haven't been able confirm but I think what happened in one case for me was something along the lines of:
> 
> * Jenkins job run against alternate branch of repo (for testing some possible changes)
> * Build.json created with a revision from that alternate branch
> * Jenkins job run against master branch again
> * Revision was not in the master branch that got checked out into the workspace thus `...build info does not exist in the git revision range`
> 
> Probably other ways this can happen as well.

You're right, we don't expect building the same build and collecting issues from different branches.
However, thanks to your feedback we are planning to support this. What we will do is to search for the latest build based on the current branch.

>... Regardless I have a build in Artifactory that has the same issue key 7 times. Each appears to be treated uniquely because the summary string after the issue key in the commit message was unique.
> 
Maybe something is wrong with your regex expression? It will help if you could share your issues collection configuration or give an example.

**Comment by bverkron** [comment]
This is the collection config:
```
{
  "version": 1,
  "issues": {
      "trackerName": "JIRA",
      "regexp": "([A-Z]{2,10}-[0-9]{1,5})(.*)",
      "keyGroupIndex": 1,
      "summaryGroupIndex": 2,
      "trackerUrl": "https://xxxx-jira.atlassian.net/browse/"
  }
}
```

**Comment by bverkron** [comment]
@Or-Geva I'm just recalling / noticing again that we have cases in production where builds are getting spammed with all the issue keys from the commit history. The latest build has 5 pages of issue keys attached to it going back almost 2 years.

This app has been built and deployed many times since then so those issues keys should "drop off" the list and not be included in subsequent builds. Our collection config is the same as posted above. Looking for some assistance.

![image](https://user-images.githubusercontent.com/19174503/204367038-c805e1f8-b28d-4408-afce-e5a110c6758a.png)

![image](https://user-images.githubusercontent.com/19174503/204368136-824eea2a-3f11-4a7b-a3a6-4c2e6c505299.png)


LET-998 issue:
![image](https://user-images.githubusercontent.com/19174503/204367459-0010cf94-27ba-492c-bbca-e01fa5336a7a.png)

**Comment by bverkron** [comment]
@Or-Geva any insights on this? It came up in discussion again internally. Does it look like a mis-configuration or a bug?

**Comment by Or-Geva** [comment]
@bverkron ,
We recommend using the JFrog Jenkins Plugin and avoid using the old Artifactory Jenkins Plugin whenever possible. 

The legacy Artifactory Jenkins Plugin will most probably not receive new features and improvements.

Both plugins can be used side by side inside the same Jenkins jobs.
