### ISSUE TITLE
Concurrent builds fail while deleting cache dir of another build running on same agent concurrently

### ISSUE THREAD

**Issue by stevn** [jfrog/jenkins-artifactory-plugin#745]
**Describe the bug**

The Jenkins Artifactory Plugin uses specific directories to store build information etc. For example:

/Users/stevn/jenkins/workspace/testproject_main@2@tmp/artifactory

Here the "@2" is inserted into the workspace directory path by Jenkins because another build is already running concurrently.

The root build dir is:

/Users/stevn/jenkins/workspace/testproject_main@2

The root temporary dir is:

/Users/stevn/jenkins/workspace/testproject_main@2@tmp

However, sometimes I see this error happening:

[testproject_main@2] $ sh -c "conan config set log.trace_file=/Users/stevn/jenkins/workspace/testproject_main@2/conan_log.log "
Parameter 'directory' is not a directory: '/Users/stevn/jenkins/workspace/testproject_main@tmp/artifactory/artifactory-pipeline-cache/22'

The interesting part here is that it seems like the plugin is trying to clean a directory outside of the current workspace. It is trying to access "testproject_main@tmp", but the current workspace is actually "testproject_main@2@tmp"! Note the inserted "@2".

For example this can be shown later in the log like this:

echo env.WORKSPACE
/Users/stevn/jenkins/workspace/testproject_main@2

So, I did some searching in the code and found this line:

https://github.com/jfrog/jenkins-artifactory-plugin/blob/df6d33af7bd5ff62bd41e9141b133d9cfbe41f70/src/main/java/org/jfrog/hudson/pipeline/declarative/steps/JfPipelinesStep.java#L124

I suspect this may be causing the problem although I have no way of testing and debugging this myself.

Here it seems to be wrong to use **getWorkspace(build.getParent())**. In other places in the code just **build.getWorkspace()** is used.

**To Reproduce**
I think it's a race condition between concurrent builds trying to clean up the Artifactory plugin cache or so. So it may be difficult to reproduce.

**Expected behavior**
Each concurrent build should only access it's own workspace, not the workspace of other builds.

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.17.0
- Jenkins operating system: 2.346.3
- Artifactory Version: 7.38.8

**Additional context**

**Comment by jagadeeswar725863** [comment]
Hello @stevn 
I am also facing concurrent download issue with following error. Could it be related to this ?
Artifactory: v3.18.0
Jenkins: v2.375.3

`19:13:13  [Thread downloader_2] downloading /tmp/1677764592903-0/2b56e28ef276024bc4a55e0ce6b370dd71e48be.zip2 as part of file xxxxxxxxx/xx8.1.0_32b56e28ef276024bc4a55e0ce6b370dd71e48be.zip threw an exception: java.io.IOException: Could not create nor write to file: /tmp/1677764592903-0/2b56e28ef276024bc4a55e0ce6b370dd71e48be.zip2
19:13:13  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.DownloadToFile.saveInputStreamToFile(DownloadToFile.java:34)
19:13:13  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.DownloadToFile.setResponse(DownloadToFile.java:40)
19:13:13  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.processResponse(JFrogService.java:143)
19:13:13  	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:123)
19:13:13  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.downloadToFile(ArtifactoryManager.java:111)
19:13:13  	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderHelper.lambda$doConcurrentDownload$0(DependenciesDownloaderHelper.java:277)
19:13:13  	at java.base/java.lang.Thread.run(Unknown Source)
19:13:13  Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 81,722,322; received: 6,469,558)
19:13:13  	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
19:13:13  	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
19:13:13  	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
19:13:13  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1309)
19:13:13  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
19:13:13  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
19:13:13  	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.DownloadToFile.saveInputStreamToFile(DownloadToFile.java:31)
19:13:13  	... 6 

Thanks.
